config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome/my_page'

  root 'articles#index'

  resources :articles do
    collection do
      post 'checkout'
      get 'checkout_new'
      post 'checkout_new'
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/card.rb
class Card < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  $edit = false
  $show = false
  def new
    @article = Article.new
    $show=false
    $edit=false
  end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        flash[:notice] = 'User was successfully created.'
        format.html { redirect_to @article }
        format.js   {}
      else
        format.js   {}
      end
    end
  end

  def index
    $show=true
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
    $edit = true
    $show=false
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def checkout
    # Apayi.client_id = '<client_id>'
    # Apayi.secret_key = '<secret_key>'
    # begin
    @article = Article.new(article_params)
    @article.save!
    #
    #   url = Apayi::Payment.checkout(article_params)
    #   if @article.send_email_check_box
    #     PaymentMailer.email_checkout_url(article_params[:user_email], url.checkout_url).deliver_now
    #   else
    #     redirect_to url.checkout_url
    #   end
    #
    # rescue Apayi::ApayiGenericError => err
    #   render :file => "/public/500.html",  :status => 500
    #   return
    # end

    redirect_to checkout_new_articles_path
  end

  def checkout_new
  end


  private
  def article_params
    params.require(:article).permit(:order_id, :amount, :currency, :user_email, :product_desc, :send_email_check_box)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def my_page
    @name = "Pratik Singh"
    @address = "Kolkata"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_error.html.erb
  <h2>
    <%= pluralize(@article.errors.count, "error") %> prohibited
    this article from being saved:
  </h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

app/views/articles/_result.html.erb
<div >
  <% if $edit and !$show%>
    <p id="success">Article successfully updated with :-
    </p>
  <%elsif !$edit and !$show%>
    <p id="success">Article successfully added with :-
    </p>
  <%else%>
    <p><label>The article details are :- <label></p>
  <% end %>
</div>
<p id="info">
 <label>Title :</label>  <%=@article.title %> </br>
 <label>Text :</label>  <%=@article.text %>
</p>

app/views/articles/checkout.html.haml
%h3 A mail has been send to your email-address. Please follow the guidelines to complete the payment.

= link_to 'Back', root_path, class: 'btn btn-info'

app/views/articles/checkout_new.html.haml
.row
  .col-lg-6
    .panel.panel-primary
      .panel-heading.center Payment Page
      .panel-body
        = form_for :card, remote: true do |f|
          .form-group
            = f.label :Card_Number
            = f.text_field :card_number, class: 'form-control', value: "4242424242424242"
          .form-group
            = f.label :Card_Holder_Name
            = f.text_field :card_holder_name, class: 'form-control', value: "Pratik"
          .form-group
            = f.label :CVV
            = f.text_field :cvv_2, class: 'form-control', value: '123'
          .form-group
            = f.label :Expiry
            = f.text_field :expiry, class: 'form-control', value: '08/20'
          = f.submit 'Pay', class: 'btn btn-success', id: 'submit'
#message

:javascript
  $(function(){
      $('#submit').off('click').on('click', function () {
          var gateway, signatures, paymentDetails, orderDetails;
          paymentDetails =  {
              mode: 'card',
              card_holder_name: $('#card_card_holder_name').val(),
              card_number: $('#card_card_number').val(),
              cvv_2: $('#card_cvv_2').val(),
              expiry: $('#card_expiry').val(),
              card_type: 'debit'
          };

          orderDetails =  {
              order_id: 'OD2',
              amount: '100.00',
              currency: 'INR',
              product_desc: 'T-shirt',
              user_email: 'pratiks@gmail.com',
              auto_capture: 'true'
          };
          signatures = {};
          signatures.merchantSignature = get_signature(signatures, '934b8583-960e-410a-a4b2-dace29e196f9', 'unRFYzoabW65OcYnyhLks02Gk+gvAuIMOfgCWIk6Xo/cB6xuREYS0Ij9c/mn6NysDsxWR7yveZTo7pSXq94U/g==');
          signatures.requestSignature = '';
          gateway = $.apayi.gateway();
          gateway.makePayment(signatures, orderDetails, paymentDetails, function(err, response) {
              if (err) {
                  $('#message').html(err);
                  return;
              }
              $('#message').html(response);
          });
      });

      var pad = function(n) {
        if (n < 10) {
          return "0" + n;
        } else {
          return n;
        }
      };
      var timestamp = function() {

        var day, dow, hours, minutes, month, now, seconds, year;
        now = new Date();
        year = now.getUTCFullYear();
        month = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][now.getUTCMonth()];
        dow = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][now.getUTCDay()];
        day = pad(now.getUTCDate());
        hours = pad(now.getUTCHours());
        minutes = pad(now.getUTCMinutes());
        seconds = pad(now.getUTCSeconds());
        return "" + dow + ", " + day + " " + month + " " + year + " " + hours + ":" + minutes + ":" + seconds + " GMT";
      };

      var get_signature = function(http_options, client_id, secret_key) {
         http_options.header = {}
         http_options.header.timestamp = timestamp();
         http_options.url = $.apayi.endpoints.production + '/api/v1/checkout/createPayment.json';
         console.log(http_options.url);
         canonical_string = 'application/x-www-form-urlencoded' + ",";
         canonical_string += '' + ",";
         canonical_string += http_options.url + "," ;
         canonical_string += http_options.header.timestamp;
        console.log(canonical_string);
         var key_signature = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA1, secret_key);
         key_signature.update(canonical_string)
         var final_signature = key_signature.finalize();
         var hmac_signature_base64 = final_signature.toString(CryptoJS.enc.Base64);
         console.log(hmac_signature_base64);
         return client_id + ":" + hmac_signature_base64;
     };

  });

app/views/articles/create.js.erb
<% if @article.errors.any? %>
    $('#results').html('');
    $('#error_explanation').html("<%= escape_javascript render(:partial => 'error') %>");

<%else%>
    clearForm()
    $('#results').html("<%= escape_javascript render(:partial => 'result') %>");
<%end%>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_for :article, url: article_path(@article), method: :patch do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  
  </p>

<% end %>

<%= link_to 'Home', articles_path %>

app/views/articles/index.html.haml
:css
  h1{
    text-align: center;
  }
%h1 All items
.table-responsive
  %table.table.table-hover.table-condensed
    %tr
      %th Order ID
      %th Amount
      %th Currency
      %th Product Description
      %th User Email
      %th Action
    - @articles.each do |article|
      %tr.articlerows{id: "#{article.id}"}
        %td= article.order_id
        %td= '%.2f' % article.amount
        %td= article.currency
        %td= article.product_desc
        %td= article.user_email
        %td= link_to 'Destroy', article_path(article), class: 'btn btn-warning', method: :delete, data: { confirm: 'Are you sure?' }
= link_to 'New Item', new_article_path, class: 'btn btn-primary'

app/views/articles/new.html.haml
:css
  .btn-checkout{
    color: #fff;
    background-color: #1E5D84;
    border-color: #1E5D84;
  }

.row
  .col-lg-6
    .panel.panel-primary
      .panel-heading.center Checkout Page
      .panel-body
        = form_for :article,url: checkout_articles_path, html: {id: 'checkout_form'} do |f|
          .form-group
            = f.label :Order_ID
            = f.text_field :order_id, class: 'form-control', value: "OD#{Faker::Number.number(10)}"
          .form-group
            = f.label :Amount
            = f.text_field :amount, class: 'form-control', value: Faker::Commerce.price + 100
          .form-group
            = f.label :Currency
            = f.text_field :currency, class: 'form-control', value: 'INR'
          .form-group
            = f.label :Product_Description
            = f.text_field :product_desc, class: 'form-control', value: Faker::Commerce.product_name
          .form-group
            = f.label :User_Email
            = f.text_field :user_email, class: 'form-control', value: ''
          .form-group
            .row
              .col-xs-12
                = f.check_box :send_email_check_box
                Send url via mail
                %br/
          = f.submit 'Proceed to Checkout', class: 'btn btn-checkout'
#results

app/views/articles/show.html.erb
<div >
  <% if $edit and !$show%>
    <p id="success">Article successfully updated with :-
    </p>
  <%elsif !$edit and !$show%>
    <p id="success">Article successfully added with :-
    </p>
  <%else%>
    <p><label>The article details are :- <label></p>
  <% end %>
</div>
<p id="info">
 <label>Title :</label>  <%=@article.title %> </br>
 <label>Text :</label>  <%=@article.text %>
</p>

app/views/articles/show.js.erb
$('.modal-body').html("<%= escape_javascript render(:partial => 'result') %>");

$('#articleModal').modal('show');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<p id="hello">Hello, Rails!</p>
<!--
<button id="change">Change</button></br>

<a href="/welcome/my_page"> My home page </a> -->
<%= link_to 'My Blog', controller: 'articles' %>

app/views/welcome/my_page.html.erb
<h1> Welcome to my home page <h1>
  <h2>
  My name is <%= @name %>. I live in  <%= @address%>
  </h2>

<h2> To go back to welcome page, click <a href="/welcome/index">here</a> <h2>